- selection:
  - brainset: 'normalized5' 
    sessions:
    - "dynamic29234-6-9-Video-021a75e56847d574b9acbcc06c675055_30hz" # 
    - "dynamic29514-2-9-Video-021a75e56847d574b9acbcc06c675055_30hz"
    - "dynamic29513-3-5-Video-021a75e56847d574b9acbcc06c675055_30hz"
    - "dynamic29156-11-10-Video-021a75e56847d574b9acbcc06c675055_30hz"
    - "dynamic17797-8-5-Video-021a75e56847d574b9acbcc06c675055_30hz" # 
    - "dynamic29228-2-10-Video-021a75e56847d574b9acbcc06c675055_30hz" # 
    - "dynamic26872-17-20-Video-021a75e56847d574b9acbcc06c675055_30hz" # 
    - "dynamic27204-5-13-Video-021a75e56847d574b9acbcc06c675055_30hz" # 
  config:
    sampling_intervals_modifier: |
      sampling_intervals = sampling_intervals & data.calcium_traces.domain & data.running.domain & data.pupil.domain
    multitask_readout:
      - readout_id: running_speed
        normalize_mean: 0 # # we export already normalized data!
        normalize_std:  1 #
        timestamp_key: running.timestamps
        value_key: running.running_speed
        metrics:
          - metric:
              # _target_: torchmetrics.MeanSquaredError
              _target_: torchmetrics.PearsonCorrCoef
              num_outputs: 1
              # _target_: torchmetrics.R2Score
              # num_outputs: 1
      - readout_id: pupil_location
        timestamp_key: pupil.timestamps
        value_key: pupil.location
        metrics:
          - metric:
              # _target_: torchmetrics.MeanSquaredError
              _target_: torchmetrics.PearsonCorrCoef
              num_outputs: 2
              # _target_: torchmetrics.R2Score
              # num_outputs: 2
      - readout_id: pupil_size_2d 
        timestamp_key: pupil.timestamps
        value_key: pupil.size
        metrics:
          - metric:
              # _target_: torchmetrics.MeanSquaredError
              _target_: torchmetrics.PearsonCorrCoef
              num_outputs: 2
              # _target_: torchmetrics.R2Score
              # num_outputs: 2
              # _target_: torchmetrics.R2Score